version: '2'

services: 
  wordpress:
    image: wordpress
    ports: 
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: root
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins
      - ./themes:/var/www/html/wp-content/themes

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - wp-db:/var/lib/mysql

volumes: 
  wp-db: