version: '2'

services: 
  wordpress:
    image: custom-wordpress
    build:
      context: .
      dockerfile: wp.Dockerfile
    ports: 
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: root

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - wp-db:/var/lib/mysql

volumes: 
  wp-db: